name: 01 All single step - direct values

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: build
        run: ./gradlew buildAllJars --no-daemon --console=plain

      - name: Create, Publish, and Deploy Package
        id: deploy
        uses: digital-ai/github-actions-deploy@D-227999
        with:
          serverUrl:     ${{ vars.SERVERURL }}
          username:      ${{ secrets.USERNAME }}
          password:      ${{ secrets.PASSWORD }}
          manifestPath:  'manifest/01-build-publish-deploy.xml'
          action:        'create_publish_deploy'
          outputPath:    'outputdar'
          versionNumber: '1.0'
          packageName:   'appForAction-1.0.dar'
          environmentId: 'Environments/envForAction1'
          rollback:      'true'

      - name: Show Action Outputs
        run: |
          echo "DAR Package Path: ${{ steps.deploy.outputs.darPackagePath }}"
          echo "Deployment Package ID: ${{ steps.deploy.outputs.deploymentPackageId }}"
          echo "Deployment Task ID: ${{ steps.deploy.outputs.deploymentTaskId }}"
          echo "Rollback Task ID: ${{ steps.deploy.outputs.rollbackTaskId }}"
