name: 04 All multiple steps - direct values
'on':
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'

      - name: Grant execute permissions to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        id: build
        run: ./gradlew buildAllJars --no-daemon --console=plain

      - name: Create DAR Package
        id: create_pkg
        uses: digital-ai/github-actions-deploy@main
        with:
          serverUrl: '${{ vars.SERVERURL }}'
          username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
          action: 'create'
          manifestPath: '/manifest/01-build-publish-deploy.xml'
          outputPath: '/outputdar'
          versionNumber: '1.0'
          packageName: 'appForAction-1.0.dar'

      - name: Show DAR Path
        run: >
          echo "DAR package created at: ${{
          steps.create_pkg.outputs.darPackagePath }}"

      - name: Publish DAR Package
        id: publish_pkg
        uses: digital-ai/github-actions-deploy@D-227999
        with:
          serverUrl: '${{ vars.SERVERURL }}'
          username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
          action: 'publish'
          darPackagePath: '${{ steps.create_pkg.outputs.darPackagePath }}'

      - name: Show Published Package ID
        run: >
          echo "Published Package ID: ${{
          steps.publish_pkg.outputs.deploymentPackageId }}"

      - name: Deploy DAR Package - Environment 1
        id: deploy_pkg
        uses: digital-ai/github-actions-deploy@D-227999
        with:
          serverUrl: '${{ vars.SERVERURL }}'
          username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
          action: 'deploy'
          deploymentPackageId: '${{ steps.publish_pkg.outputs.deploymentPackageId }}'
          environmentId: 'Environments/envForAction1'

      - name: Show Deployment Task IDs
        run: >
          echo "Deployment Task ID: ${{
          steps.deploy_pkg.outputs.deploymentTaskId }}"

          echo "Rollback Task ID (if any): ${{
          steps.deploy_pkg.outputs.rollbackTaskId }}"
